////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$SendNudes", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class SendNudesPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        #endregion

        #region Methods

        public static string ReturnHelp() => "$SendNudes CHARACTERNAME";

        #endregion
    }
}